
###
POST http://localhost:5000/blog/admin/blog
Content-Type:  application/json

{
  "data":{"limit":1,"skip":0,"userId":"64996ff8617d55e8b12046c3"}
}

###
POST http://localhost:5000/blog/admin/search
Content-Type:  application/json

{
  "data":{"search":"lực","userId":"649eb8529eeb9ff7df44758b"}
}